services:
  product_micro:
    build: ./productservices
    container_name: product_cont
    ports:
      - 8000:8000
    depends_on:
      - postgres_db
      - broker
    volumes:
      - ./productservices:/code

  consumer_services:
      build:  
        context: ./consumer
        dockerfile: Dockerfile
      container_name: consumer_cont
      ports:
        - 8001:8001
      depends_on:
        - postgres_consumer_db
        - broker
      volumes:
        - ./consumer:/code



  postgres_db:
    image: postgres:latest
    restart: always
    container_name: PostgresCont
    environment:
      - POSTGRES_USER=ziakhan
      - POSTGRES_PASSWORD=my_password
      - POSTGRES_DB=mydatabase
    ports:
      - '5433:5432'
    volumes:
      - postgres_db:/var/lib/postgresql/data

  postgres_consumer_db:
    image: postgres:latest
    restart: always
    container_name: PostgresContConsumer
    environment:
      - POSTGRES_USER=ziakhan
      - POSTGRES_PASSWORD=my_password
      - POSTGRES_DB=mydatabase
    ports:
      - '5434:5432'  
    volumes:
      - postgres_consumer_db:/var/lib/postgresql/data

  broker:
    image: apache/kafka:latest
    container_name: broker
    ports:
      - '9092:9092'
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_LISTENERS: PLAINTEXT://broker:9092,CONTROLLER://broker:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://broker:9092
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@broker:9093
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_NUM_PARTITIONS: 3
      
  kafka-ui:
    container_name: kafka-ui
    image: provectuslabs/kafka-ui:latest
    ports:
      - 8080:8080
    depends_on:
      - broker  
    environment:
      DYNAMIC_CONFIG_ENABLED: 'true'
      KAFKA_CLUSTERS_0_NAME: 'Local Kafka Cluster'
      KAFKA_CLUSTERS_0_BOOTSTRAP_SERVERS: 'broker:9092'

networks:
  default:
    driver: bridge

volumes:
  postgres_db:
    driver: local
  postgres_consumer_db: 
    driver: local


